[metadata]
name = ephyr
version = attr: ephyr.version.__version__
description = Ephyr: an open-source platform for visualizing and labeling multimodal electrophysiological data
long_description = file: README.md
long_description_content_type = text/markdown
keywords = Ephyr, EEG, electrophysiology, signal, ephys, MEA, trace
license_files =
    LICENSE
classifiers =
    Programming Language :: Python :: 3
    Environment :: Console
    Environment :: Other Environment
    Environment :: Web Environment
    Intended Audience :: Developers
    Intended Audience :: End Users/Desktop
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Natural Language :: English
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    Programming Language :: Python :: 3 :: Only
author = LIFT center

[options]
zip_safe = False
include_package_data = True
packages = find:
python_requires = >=3.11
install_requires =
    PyQt6>=6.7.0
    numpy~=2.2.0
    pandas>=2.2.0
    open-ephys-python-tools>=1.0.1
    pydantic>=2.11.9
    platformdirs~=4.3.8
    scipy>=1.14.0
    pymatreader>=1.2.0
    tomli>=2.0.0 ; python_version < "3.11"
    pyabf>=2.3.8
    pyedflib>=0.1.42
    pynwb>=4.0.0


[options.extras_require]
dev =
    pyqt6-tools>=6.7.0.0.3

[options.entry_points]
console_scripts =
    ephyr = ephyr.gui.entrypoint:main

;[options.package_data]
;ephyr.ui.gui.uis._qt_assets = icons/light/*, icons/dark/*, fonts/*.ttf, images/*

[options.packages.find]
exclude =
    .debug*
    .ipynb_checkpoints
    examples*
    devtools*
    docs*
    tests*
    venv*
